/* config.h - Generated by CMake */

#ifndef CONFIG_H
#define CONFIG_H

/* Package information */
#define PACKAGE "@PROJECT_NAME@"
#define PACKAGE_NAME "@PROJECT_NAME@"
#define PACKAGE_VERSION "@PROJECT_VERSION@"
#define VERSION "@PROJECT_VERSION@"
#define PACKAGE_STRING "@PROJECT_NAME@ @PROJECT_VERSION@"
#define PACKAGE_TARNAME "@PROJECT_NAME@"

/* Gettext package */
#define GETTEXT_PACKAGE "@GETTEXT_PACKAGE@"

/* Installation directories */
#define PREFIX "@CMAKE_INSTALL_PREFIX@"
#define XCHATLIBDIR "@PCHAT_LIBDIR@"
#define XCHATSHAREDIR "@PCHAT_SHAREDIR@"
#define ISO_CODES_LOCALEDIR "@ISO_CODES_LOCALEDIR@"

/* Optional features */
#cmakedefine USE_OPENSSL 1
#cmakedefine USE_IPV6 1
#cmakedefine USE_PLUGIN 1
#cmakedefine USE_GMODULE 1
#cmakedefine USE_DBUS 1
#cmakedefine USE_LIBNOTIFY 1
#cmakedefine USE_LIBCANBERRA 1
#cmakedefine USE_LIBPROXY 1
#cmakedefine SOCKS 1

/* System detection */
#cmakedefine USING_LINUX 1
#cmakedefine USING_FREEBSD 1
#cmakedefine OS_W32 1

/* Windows compatibility - must come after system detection */
#ifdef _WIN32
#include <winsock2.h>
#include <ws2tcpip.h>
#ifndef socklen_t
typedef int socklen_t;
#endif
#ifndef INET_ADDRSTRLEN
#define INET_ADDRSTRLEN 16
#endif
#ifndef INET6_ADDRSTRLEN
#define INET6_ADDRSTRLEN 46
#endif
#endif

/* Linux/UNIX specific - memrchr is a GNU extension */
#if defined(USING_LINUX) || defined(__linux__) || defined(__gnu_linux__)
#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif
#define HAVE_MEMRCHR 1
#endif

/* System headers */
#cmakedefine HAVE_SYS_TYPES_H 1
#cmakedefine HAVE_SYS_STAT_H 1
#cmakedefine HAVE_STDLIB_H 1
#cmakedefine HAVE_STRING_H 1
#cmakedefine HAVE_MEMORY_H 1
#cmakedefine HAVE_STRINGS_H 1
#cmakedefine HAVE_INTTYPES_H 1
#cmakedefine HAVE_STDINT_H 1
#cmakedefine HAVE_UNISTD_H 1

/* Functions */
#cmakedefine HAVE_MEMSET 1
#cmakedefine HAVE_STRCASECMP 1
#cmakedefine HAVE_STRDUP 1
#cmakedefine HAVE_STRTOUL 1

#endif /* CONFIG_H */
